# Generated by Django 5.2.3 on 2025-06-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='espacio_fisico',
            new_name='espacio',
        ),
        migrations.AlterField(
            model_name='area',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='dni',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='socio',
            name='apellido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
